import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowUpRight, CheckCircle2, Clock3, ExternalLink, Plus, Search, Users, X, type LucideIcon } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from '../api'
import type { DailyUpdate, Member, Summary } from '../types'
import './member-modal.css'
import './member-detail.css'

const today = new Date().toLocaleDateString('en-CA')
const colors: Record<string,string> = {'Completed':'#13866f','On track':'#57a55a','In progress':'#e4a63b','Blocked':'#d95a4e','No progress today':'#88938f'}

export default function Dashboard() {
  const [date,setDate]=useState(today), [summary,setSummary]=useState<Summary|null>(null)
  const [updates,setUpdates]=useState<DailyUpdate[]>([]), [missing,setMissing]=useState<Member[]>([])
  const [members,setMembers]=useState<Member[]>([]), [memberSearch,setMemberSearch]=useState('')
  const [selectedMember,setSelectedMember]=useState<Member|null>(null), [memberHistory,setMemberHistory]=useState<DailyUpdate[]>([]), [loadingHistory,setLoadingHistory]=useState(false)
  const [showMemberForm,setShowMemberForm]=useState(false), [memberMessage,setMemberMessage]=useState(''), [savingMember,setSavingMember]=useState(false)
  const loadDashboard=useCallback(()=>{ Promise.all([api.summary(date),api.updates(date),api.missing(date),api.members()]).then(([s,u,m,all])=>{setSummary(s);setUpdates(u);setMissing(m);setMembers(all)}).catch(()=>{}) },[date])
  useEffect(()=>{ loadDashboard() },[loadDashboard])
  async function addMember(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSavingMember(true); setMemberMessage('')
    const form=event.currentTarget, data=new FormData(form)
    try {
      await api.createMember(Object.fromEntries(data.entries()) as Omit<Member,'id'>)
      if (form.isConnected) form.reset()
      setMemberMessage('Member added successfully.'); loadDashboard()
      window.setTimeout(()=>{setShowMemberForm(false);setMemberMessage('')},900)
    } catch(err) { setMemberMessage(err instanceof Error ? err.message : 'Unable to add member') }
    finally { setSavingMember(false) }
  }
  async function openMember(member: Member) {
    setSelectedMember(member); setMemberHistory([]); setLoadingHistory(true)
    try { setMemberHistory(await api.memberUpdates(member.id)) } finally { setLoadingHistory(false) }
  }
  const statuses=useMemo(()=>Object.entries(updates.reduce<Record<string,number>>((a,u)=>{a[u.current_status]=(a[u.current_status]||0)+1;return a},{})).map(([name,value])=>({name,value})),[updates])
  const teams=useMemo(()=>Object.values(updates.reduce<Record<string,{team:string,hours:number}>>((a,u)=>{const team=u.member?.team||'Unknown';a[team]??={team,hours:0};a[team].hours+=Number(u.hours_spent);return a},{})),[updates])
  const cards: [string, string | number, string, LucideIcon][]=[['Submission rate',`${summary?.submission_rate??0}%`,`${summary?.submitted??0} of ${summary?.active_members??0} members`,Users],['Hours reported',summary?.total_hours??0,'Across all teams',Clock3],['Completed',summary?.completed??0,'Deliverables today',CheckCircle2],['Active blockers',summary?.blocked??0,`${summary?.high_priority_blockers??0} high priority`,AlertTriangle]]
  const visibleMembers=members.filter(member=>`${member.full_name} ${member.team} ${member.role}`.toLowerCase().includes(memberSearch.toLowerCase()))
  const historyHours=memberHistory.reduce((sum,item)=>sum+Number(item.hours_spent),0)
  return <div className="dashboard-page">
    <div className="dashboard-header"><div><span className="eyebrow">Barnum's command center</span><h1>Daily sprint overview</h1><p>Delivery health, contribution signals, and obstacles requiring attention.</p></div><div className="dashboard-actions"><label className="date-filter">Reporting date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="add-member-button" onClick={()=>setShowMemberForm(true)}><Plus size={17}/> Add member</button></div></div>
    <section className="metric-grid">{cards.map(([label,value,note,Icon])=><article className="metric-card" key={String(label)}><div><span>{label as string}</span><strong>{value as string|number}</strong><small>{note as string}</small></div><span className="metric-icon"><Icon size={20}/></span></article>)}</section>
    <section className="dashboard-grid">
      <article className="panel member-panel"><div className="panel-title"><div><h2>Member activity</h2><p>Select a member to review their contribution history</p></div><span className="count-badge muted">{members.length} members</span></div><label className="member-search"><Search size={15}/><input value={memberSearch} onChange={event=>setMemberSearch(event.target.value)} placeholder="Search member, team, or role…"/></label><div className="member-table"><div className="member-table-head"><span>Member</span><span>Team and role</span><span>Today's status</span><span>Hours</span><span></span></div>{visibleMembers.map(member=>{const update=updates.find(item=>item.member_id===member.id);return <button key={member.id} onClick={()=>openMember(member)}><span className="member-identity"><i className="avatar">{member.full_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</i><strong>{member.full_name}<small>{member.email}</small></strong></span><span>{member.team}<small>{member.role}</small></span><span>{update?<i className="status-pill" style={{background:colors[update.current_status]+'18',color:colors[update.current_status]}}>{update.current_status}</i>:<i className="status-pill missing">Not submitted</i>}</span><span>{update?`${update.hours_spent}h`:'—'}</span><ArrowUpRight size={16}/></button>})}</div></article>
      {selectedMember&&<div className="modal-backdrop detail-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setSelectedMember(null)}}><section className="member-detail" role="dialog" aria-modal="true" aria-labelledby="member-detail-title"><button className="modal-close" aria-label="Close" onClick={()=>setSelectedMember(null)}><X size={18}/></button><header><span className="avatar large">{selectedMember.full_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><span className="eyebrow">Member drill-down</span><h2 id="member-detail-title">{selectedMember.full_name}</h2><p>{selectedMember.team} · {selectedMember.role} · {selectedMember.email}</p></div></header>{loadingHistory?<div className="detail-loading">Loading contribution history…</div>:<><div className="detail-metrics"><div><strong>{memberHistory.length}</strong><span>Updates</span></div><div><strong>{historyHours.toFixed(1)}</strong><span>Total hours</span></div><div><strong>{memberHistory.filter(item=>item.current_status==='Completed').length}</strong><span>Completed</span></div><div><strong>{memberHistory.filter(item=>item.current_status==='Blocked').length}</strong><span>Blocked days</span></div></div><div className="history-list">{memberHistory.map(item=><article key={item.id}><div className="history-date"><strong>{new Date(`${item.reporting_date}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</strong><small>{new Date(`${item.reporting_date}T12:00:00`).getFullYear()}</small></div><div className="history-content"><div><span className="status-pill" style={{background:colors[item.current_status]+'18',color:colors[item.current_status]}}>{item.current_status}</span><span className="hours-pill">{item.hours_spent}h</span></div><h3>{item.sprint_goal}</h3><p><strong>Completed:</strong> {item.completed_today}</p>{item.current_status==='Blocked'&&<p className="history-blocker"><AlertTriangle size={14}/><span><strong>{item.blocker_severity} blocker:</strong> {item.blocker_details} · Owner: {item.dependency_owner}</span></p>}<p><strong>Next:</strong> {item.plan_tomorrow}</p>{item.supporting_evidence&&<a href={item.supporting_evidence} target="_blank" rel="noreferrer"><ExternalLink size={13}/> Supporting evidence</a>}</div></article>)}{memberHistory.length===0&&<div className="empty">No daily updates have been submitted yet.</div>}</div></>}</section></div>}
      <article className="panel chart-panel"><div className="panel-title"><div><h2>Team effort</h2><p>Hours reported by team today</p></div></div><ResponsiveContainer width="100%" height={245}><BarChart data={teams} margin={{left:-20}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="team" tick={{fontSize:11}}/><YAxis/><Tooltip/><Bar dataKey="hours" fill="#176c65" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></article>
      <article className="panel status-panel"><div className="panel-title"><div><h2>Delivery status</h2><p>Today's update distribution</p></div></div><div className="status-chart"><ResponsiveContainer width="55%" height={215}><PieChart><Pie data={statuses} dataKey="value" nameKey="name" innerRadius={58} outerRadius={82} paddingAngle={3}>{statuses.map(s=><Cell key={s.name} fill={colors[s.name]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="legend">{statuses.map(s=><div key={s.name}><i style={{background:colors[s.name]}}/><span>{s.name}</span><strong>{s.value}</strong></div>)}</div></div></article>
      <article className="panel blocker-panel"><div className="panel-title"><div><h2>Blocker command center</h2><p>Items needing coordination or action</p></div><span className="count-badge">{summary?.blocked??0} open</span></div><div className="table-wrap"><table><thead><tr><th>Member</th><th>Team</th><th>Blocker</th><th>Severity</th><th>Owner</th></tr></thead><tbody>{updates.filter(u=>u.current_status==='Blocked').map(u=><tr key={u.id}><td><strong>{u.member?.full_name}</strong></td><td>{u.member?.team}</td><td>{u.blocker_details}</td><td><span className={`severity ${(u.blocker_severity||'').toLowerCase()}`}>{u.blocker_severity}</span></td><td>{u.dependency_owner}</td></tr>)}{!updates.some(u=>u.current_status==='Blocked')&&<tr><td colSpan={5} className="empty"><CheckCircle2 size={20}/> No blockers reported for this date.</td></tr>}</tbody></table></div></article>
      <article className="panel missing-panel"><div className="panel-title"><div><h2>Missing updates</h2><p>Members who have not checked in</p></div><span className="count-badge muted">{missing.length}</span></div><div className="missing-list">{missing.slice(0,6).map(m=><div key={m.id}><span className="avatar">{m.full_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><strong>{m.full_name}</strong><small>{m.team} · {m.role}</small></div><ArrowUpRight size={16}/></div>)}{missing.length===0&&<div className="empty"><CheckCircle2 size={20}/> Everyone has submitted.</div>}</div></article>
    </section>
    {showMemberForm&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setShowMemberForm(false)}}><section className="member-modal" role="dialog" aria-modal="true" aria-labelledby="member-modal-title"><button className="modal-close" aria-label="Close" onClick={()=>setShowMemberForm(false)}><X size={18}/></button><span className="eyebrow">Team administration</span><h2 id="member-modal-title">Add a team member</h2><p>Create a member record so they can submit daily updates and appear in reporting.</p><form onSubmit={addMember}><label>Full name<input name="full_name" placeholder="Jordan Lee" required minLength={2}/></label><label>ASU ID<input name="asu_id" placeholder="jlee123" required minLength={2}/></label><label className="wide">ASU email address<input name="email" type="email" placeholder="jordan.lee@asu.edu" required/></label><label>Team<select name="team" required defaultValue=""><option value="" disabled>Select team</option>{['Agentic AI','Infrastructure','OTel','Security','Testing'].map(v=><option key={v}>{v}</option>)}</select></label><label>Role<select name="role" required defaultValue="Contributor">{['Team Lead','Technical Lead','Module Owner','Contributor','Reviewer','Tester'].map(v=><option key={v}>{v}</option>)}</select></label>{memberMessage&&<div className={`member-message wide ${memberMessage.startsWith('Member')?'success':''}`}>{memberMessage}</div>}<div className="modal-actions wide"><button type="button" className="secondary-button" onClick={()=>setShowMemberForm(false)}>Cancel</button><button type="submit" className="primary-button" disabled={savingMember}>{savingMember?'Adding member…':'Add member'}</button></div></form></section></div>}
  </div>
}
